name: Generate Photo Map (Leaflet)

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分ごと
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # PyGithubでindex.htmlやキャッシュを更新するため
    env:
      # === Secrets を使用 ===
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
      SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # PATでもOK、無ければ自動のGITHUB_TOKENでも可
      REPO_NAME: ${{ secrets.REPO_NAME }}         # 例: K03-02/photomap
      HTML_NAME: index.html
      BRANCH_NAME: main
      CACHE_FILE: photomap_cache.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow pyheif exifread PyGithub pandas

      - name: Run generator
        run: python scripts/generate_map.py
