name: Generate Photo Map

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # HEIC 対応ライブラリをインストール
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libheif-examples libheif-dev libde265-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib \
                      pillow pyheif exifread PyGithub pandas requests

      # HEIC が GitHub Actions 上で読めるか確認するテスト
      - name: Test HEIC support
        run: |
          python - <<'EOF'
          import pyheif
          from PIL import Image, UnidentifiedImageError

          try:
              path = "tests/sample.heic"
              heif_file = pyheif.read(path)
              image = Image.frombytes(
                  heif_file.mode, heif_file.size, heif_file.data, "raw", heif_file.mode
              )
              print("✅ HEIC読み込み成功:", image.size)
          except FileNotFoundError:
              print("⚠️ sample.heic が存在しません（テストスキップ）")
          except UnidentifiedImageError:
              print("❌ HEIC 読み込み失敗: Pillow が対応していません")
          except Exception as e:
              print("❌ HEIC エラー:", e)
          EOF

      # サービスアカウントキーを環境変数にセット
      - name: Set SERVICE_ACCOUNT_B64
        run: echo "SERVICE_ACCOUNT_B64 is set"
        env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}

      - name: Run generate_map.py
        env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
        run: python scripts/generate_map.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output


