name: photomap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_OAUTH_B64: ${{ secrets.USER_OAUTH_B64 }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pillow-heif exifread PyGithub google-api-python-client google-auth google-auth-oauthlib pandas

      - name: Run photomap script
        run: python scripts/generate_map.py
