name: Generate Photo Map
on:
  workflow_dispatch:  # 手動実行対応

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas pillow pillow-heif exifread PyGithub google-api-python-client google-auth google-auth-oauthlib

    - name: Run generate_map.py
      env:
        USER_OAUTH_B64: ${{ secrets.USER_OAUTH_B64 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/generate_map.py
