name: Generate Photo Map

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas pillow pillow-heif exifread PyGithub google-api-python-client google-auth google-auth-oauthlib

      - name: Run generate_map.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_OAUTH_B64: ${{ secrets.USER_OAUTH_B64 }}
          PNG_FOLDER_ID: ${{ secrets.PNG_FOLDER_ID }}
        run: python scripts/generate_map.py

