name: Generate Photo Map

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CACHE_FILE: /tmp/photomap_cache.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache photomap_cache.json
        uses: actions/cache@v3
        with:
          path: /tmp/photomap_cache.json
          key: photomap-cache-${{ hashFiles('scripts/generate_map.py') }}
          restore-keys: |
            photomap-cache-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow pyheif exifread PyGithub pandas

      - name: Configure Google Service Account
        run: |
          echo "$SERVICE_ACCOUNT_B64" | base64 --decode > /tmp/service_account.json
        env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service_account.json" >> $GITHUB_ENV

      - name: Run generate_map.py
        run: python scripts/generate_map.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
