name: Generate Photo Map

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: 'K03-02/photomap'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow pyheif exifread PyGithub pandas

    - name: Setup Google Credentials
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 --decode > /tmp/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json

    - name: Run generate_map.py
      run: python scripts/generate_map.py
