name: Generate Photo Map

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 毎日 2:00

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth pyheif exifread Pillow PyGithub pandas

      - name: Run generate_map.py
        run: python scripts/generate_map.py
