name: Generate Photo Map

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # GitHub Secret に保存した base64 エンコード済みサービスアカウントJSON
      SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow pyheif exifread google-api-python-client google-auth PyGithub

    - name: Decode service account JSON
      run: |
        echo "$SERVICE_ACCOUNT_B64" | base64 --decode > sa.json

    - name: Run generate_map.py
      run: python scripts/generate_map.py
      env:
        SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
