name: Update Photo Map

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごと
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pillow pyheif exifread google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib PyGithub

      - name: Decode service account
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_B64 }}" | base64 --decode > /tmp/service_account.json

      - name: Run generate_map.py
        env:
          SERVICE_ACCOUNT_FILE: /tmp/service_account.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/generate_map.py
