name: Update Photo Map

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごと

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow pyheif exifread PyGithub
      - name: Run update script
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: python update_photos.py
