name: Update Photo Map

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow pyheif exifread PyGithub

      - name: Run update script
        run: python your_script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
