name: Generate Photo Map

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}  # Secret を環境変数に渡す
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode service account
        run: |
          echo "$SERVICE_ACCOUNT_B64" | base64 --decode > sa.json

      - name: Generate Map
        run: |
          python scripts/generate_map.py
